apiVersion: v1
kind: Secret
metadata:
  name: otus-user-secret
type: Opaque
data:
  DATASOURCE_URL: {{ printf "jdbc:postgresql://postgres:%s/%s" .Values.postgresql.service.port .Values.postgresql.postgresqlDatabase  | b64enc | quote }}
  DATASOURCE_USERNAME: {{ printf "%s" .Values.postgresql.postgresqlUsername | b64enc | quote }}
  DATASOURCE_PASSWORD: {{ printf "%s" .Values.postgresql.postgresqlPassword  | b64enc | quote }} 
