apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name:  {{ include "otus-api-gateway-chart.fullname" . }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - host: {{ .Values.host }}
    http:
      paths:
        - path: {{ .Values.routePrefix }}($|/)(.*)
          pathType: Prefix
          backend:
            service:
              name: {{ include "otus-api-gateway-chart.fullname" . }}
              port: 
                number: {{ .Values.service.port }}
